@id = 1
### LOGIN
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}

### read a file with users
GET http://localhost:8080/users/xml

### add users from xml file
POST http://localhost:8080/users/xml

### receive all users
GET http://localhost:8080/users

### receive user by id
GET http://localhost:8080/users/{{id}}

### add user
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": 1,
  "personalInfo": {
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "dateOfBirth": "1981-05-06",
    "gender": "Male"
  },
  "education": {
    "universityName": "Example University",
    "degree": "Bachelor's in Computer Science",
    "graduationYear": 2014
  },
  "employment": {
    "companyName": "Example Corp",
    "position": "Software Engineer",
    "startDate": "2015-06-01",
    "endDate": "Present"
  },
  "contactInfo": {
    "phoneNumber": "+1234567890",
    "address": {
      "street": "123 Cool Street",
      "city": "New York",
      "state": "NY",
      "postalCode": 10001,
      "country": "USA"
    }
  },
  "skills": ["Java", "Spring Boot", "MongoDB", "REST API"]
}


### update user
PUT http://localhost:8080/users/{{id}}
Content-Type: application/json01 ysxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
{
  "personalInfo": {
    "firstName": "John123",
    "lastName": "Doe123",
    "email": "john123.doe123@example.com",
    "dateOfBirth": "1981-05-06",
    "gender": "Male"
  },
  "education": {
    "universityName": "Example University",
    "degree": "Bachelor's in Computer Science",
    "graduationYear": 2014
  },
  "employment": {
    "companyName": "Example Corp",
    "position": "Software Engineer",
    "startDate": "2015-06-01",
    "endDate": "Present"
  },
  "contactInfo": {
    "phoneNumber": "+1234567890",
    "address": {
      "street": "123 Cool Street",
      "city": "New York",
      "state": "NY",
      "postalCode": 10001,
      "country": "USA"
    }
  },
  "skills": ["Java", "Spring Boot", "MongoDB", "REST API"]
}

### delete user
DELETE http://localhost:8080/users/{{id}}