### GET request to example server
GET http://localhost:8080/users/ping

###

### POST request to MongoDb in Docker container
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": 1,
  "personalInfo": {
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "dateOfBirth": "1981-05-06",
    "gender": "Male"
  },
  "education": {
    "universityName": "Example University",
    "degree": "Bachelor's in Computer Science",
    "graduationYear": 2014
  },
  "employment": {
    "companyName": "Example Corp",
    "position": "Software Engineer",
    "startDate": "2015-06-01",
    "endDate": "Present"
  },
  "contactInfo": {
    "phoneNumber": "+1234567890",
    "address": {
      "street": "123 Cool Street",
      "city": "New York",
      "state": "NY",
      "postalCode": 10001,
      "country": "USA"
    }
  },
  "skills": ["Java", "Spring Boot", "MongoDB", "REST API"]
}

###

### PUT request to MongoDb in Docker container
@id = 1
PUT http://localhost:8080/users/{{id}}
Content-Type: application/json

{
  "personalInfo": {
    "firstName": "John123",
    "lastName": "Doe123",
    "email": "john123.doe123@example.com",
    "dateOfBirth": "1981-05-06",
    "gender": "Male"
  },
  "education": {
    "universityName": "Example University",
    "degree": "Bachelor's in Computer Science",
    "graduationYear": 2014
  },
  "employment": {
    "companyName": "Example Corp",
    "position": "Software Engineer",
    "startDate": "2015-06-01",
    "endDate": "Present"
  },
  "contactInfo": {
    "phoneNumber": "+1234567890",
    "address": {
      "street": "123 Cool Street",
      "city": "New York",
      "state": "NY",
      "postalCode": 10001,
      "country": "USA"
    }
  },
  "skills": ["Java", "Spring Boot", "MongoDB", "REST API"]
}

###

### DELETE request to MongoDb in Docker container

DELETE http://localhost:8080/users/{{id}}

###